Correct yadm project directory for Windows yadm updating

diff --git a/.config/yadm/bootstrap b/.config/yadm/bootstrap
--- a/.config/yadm/bootstrap
+++ b/.config/yadm/bootstrap
@@ -48,10 +48,10 @@ if $IS_WINDOWS_GIT_BASH; then
         echo "PowerShell bootstrap failed with exit code $?"
     fi
 
-    if [[ -d "$HOME/.yadm-directory" ]]; then
+    if [[ -d "$HOME/.yadm-project" ]]; then
         # Linux installations use a package manager so yadm gets updated with apt update
         echo Updating yadm on Windows
-        cd "$HOME/.yadm-directory" || { echo "Failed to cd into .yadm-directory"; exit 1; }
+        cd "$HOME/.yadm-project" || { echo "Failed to cd into .yadm-project"; exit 1; }
         git pull
         cd "$HOME" || { echo "Failed to cd back to HOME"; exit 1; }
     fi
